name: "stable-release"

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  tests:
    uses: "./.github/workflows/unit-tests.yml"  # use the callable tests job to run tests

  pre-release:
    name: "GitHub Release"
    needs: [tests]
    runs-on: "ubuntu-latest"
    steps:
      - name: "Releasing"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "stable"
          prerelease: false
          title: "Stable Build"

  pypi-release:
    name: "PyPI Release"
    needs: [tests, pre-release]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m build
          twine upload dist/*